# This file was generated by GoReleaser. DO NOT EDIT.
class Taskmaster < Formula
  desc "Taskmaster is a better way to manage your tasks."
  homepage "https://github.com/SimantovYousoufov/taskmaster"
  version "0.0.5"

  if OS.mac?
    url "https://github.com/SimantovYousoufov/taskmaster/releases/download/v0.0.5/taskmaster_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "388d6ed0832fe82280a9deaf04580319aff8ad13cd0525b3e5e2745ba26c047e"
  elsif OS.linux?
    url "https://github.com/SimantovYousoufov/taskmaster/releases/download/v0.0.5/taskmaster_0.0.5_Linux_x86_64.tar.gz"
    sha256 "beec8fdd79bd99fc993fdc80a92afe3f2a66e4b03aa5824fa3fe1a3238eabb5c"
  end

  def install
    bin.install "tkm"
  end

  test do
    system "#{bin}/tkm --version"
  end
end
