# This file was generated by GoReleaser. DO NOT EDIT.
class Taskmaster < Formula
  desc "Taskmaster is a better way to manage your tasks."
  homepage "https://github.com/SimantovYousoufov/taskmaster"
  version "0.1.3"

  if OS.mac?
    url "https://github.com/SimantovYousoufov/taskmaster/releases/download/v0.1.3/taskmaster_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "52780d58bafce5093db7f39044618c3fcb675779cb24487ebf8100fdfe57f8dc"
  elsif OS.linux?
    url "https://github.com/SimantovYousoufov/taskmaster/releases/download/v0.1.3/taskmaster_0.1.3_Linux_x86_64.tar.gz"
    sha256 "ae1933fa0b3af7eebc09f8f0180c549b0245dd6bc5d9a5e58ee72aa1b7478ccb"
  end

  def install
    bin.install "tkm"
  end

  test do
    system "#{bin}/tkm --version"
  end
end
